name: Sync from Upstream da-cloud-commondatabase

on:
  schedule:
    - cron: "0 2 * * *"  # Every day at 2 AM UTC
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout your repo
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.DA_SYNC_TOKEN }}
        fetch-depth: 0

    - name: Set up Git identity
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

    - name: Add upstream and fetch
      run: |
        git remote | grep upstream || git remote add upstream https://github.com/wwwdageparty/da-cloud-commondatabase.git
        git fetch upstream

    - name: Force sync with upstream
      run: |
        git checkout master
        git reset --hard upstream/master
        git push origin master --force
